IrinaKorsun/SberbankReboot

Task_01/src/main/java/radionov/Task01.java

Task-01 from Radionov

---

Task_01/src/main/java/chernoskutov/Task_01.java

Task 01 complete

---

Lesson_02/src/main/java/tishchenko/task_01/Array.java

…метода сортировки нашел минимальное,максимальное и среднее знаение массива.
Так же учел нюанс, если длина массива будет четной и в таком слуаче средним значением будут являтся 2 числа массива.

feature-02-tishchenko

---

.idea/vcs.xml
Task_01/src/main/java/sarapulova/HelloWord.java

Feature 01 sarapulova

---

Lesson_01/src/main/java/kurkin/Task_01.java

Lesson_1 initial PR. Please.....

feature-01-kurkin. Initial commit

---

Lesson_02/src/main/java/sarapulova/Task_02_ArrMinMaxAvr.java
Lesson_02/src/main/java/sarapulova/Task_02_Calc.java

В массивах попробовала использовать консоль, поборолась немного с кодировками на русском :)
В калькуляторе неплохо бы разнести вычисления в один класс, ввод в другой и из main только все дергать, но как я понимаю, это будет дальше.

feature-02-sarapulova   min,max,avg in array and calculator

---

Lesson_01/src/main/java/shevnin/HelloWorld.java
Lesson_02/src/main/java/shevnin/RamdomArray.java

Выполнение ДЗ по уроку 1 и уроку 2

ShevninKA Task01 & Task02

---

Task_01/src/main/java/torikov/Task1HelloWorld.java

Попровил branch, вынес в отдельный package. Вроде теперь всё корректно...

feature-01-torikov

---

Lesson_02/src/main/java/radionov/Task02.java

Мой вариант выполнения задания с калькулятором

feature-lesson02-task02 by Radionov

---

Lesson_02/src/main/java/chernoskutov/ArrRandom.java
Lesson_02/src/main/java/chernoskutov/Calc.java

Feature 02 chernoskutov

---

Lesson_02/src/main/java/tishchenko/task_02/Calc.java

Реализовал просто калькулятор с возможностью выполнения простых операций - сложение,вычитание,умножение,деление.
Запуск происходит в цикле while, предоставляя пользователю возможность продолжить использование калькулятора после первого использования.

feature-03-tishchenko(SimpleCalc)

---

Lesson_01/src/main/java/shevnin/HelloWorld.java
Lesson_02/src/main/java/shevnin/Calc.java
Lesson_02/src/main/java/shevnin/RamdomArray.java

Feature lesson02 shevnin

---

Lesson_01/src/main/java/kasyanov/Task_01.java
Lesson_02/src/main/java/kasyanov/Task_01_Array.java
Lesson_02/src/main/java/kasyanov/Task_02_Calculator.java
Task_01/src/main/java/kasyanov/Task_01.java
Task_01/src/main/java/kasyanov/Task_02_02_Calculator.java
Task_01/src/main/java/kasyanov/Task_02_Arrray.java

Feature kasyanov task 01

---

Lesson_03/pom.xml
Lesson_03/src/main/java/chernoskutov/task_01/Task_01.java
Lesson_03/src/main/java/chernoskutov/task_01/Vector.java

task01. Поднял версию Java в проекте до 1.8

lesson3-task01 20191024

---

Lesson_03/src/main/java/sharoyko/Task_01/Task_01.java

Прошу обратить внимание на информацию в javadoc в начале кода.

Feature Lesson_03_Task_01: create Class Vector

---

Lesson_02/src/main/java/melnikov/Task_01/Task_2.java
Lesson_02/src/main/java/melnikov/Task_02/Task_2_1.java

Повторно создал request, ранее закрытый request № 33 не разобрался как открыть.
Все ранее озвученные рекомендации учтены

bugfix: refactoring code

---

Task_01/src/main/java/torikov/Task1HelloWorld.java
Task_02/src/main/java/torikov/Task2_1MinMax.java
Task_02/src/main/java/torikov/Task2_2Calc.java

Как по мне, не хватает исключения на проверку число\не число, но мы же исключения ещё не проходили)). Остальное вроде работает исправно.

Feature 02 2 torikov

---

Lesson_03/src/main/java/polenok/task_01/task_01.java

feature-03-polenok-task-01

---

Lesson_03/src/main/java/tishchenko/Task01/VectorMain.java

Выполнил задание по операциям над векторами
Начальные данные векторов и элемент массива задается в классе VectorMain

feature-03-tishchenko-Task01(Vectors)

---

Lesson_03/src/main/java/polenok/task_02/Task_02_Queue.java
Lesson_03/src/main/java/polenok/task_02/Task_02_Stack.java

feature-03-polenok-task-02

---

Lesson_03/src/main/java/torikov/Task01Vector/Main.java
Lesson_03/src/main/java/torikov/Task01Vector/Vector.java

Операции с векторами. Сразу скажу, небыло времени в коде проверять корректность ввода данных пользователем (если выбор происходит не из предложенных  программой вариантов).

feature-03_1-torikov

---

Lesson_02/src/main/java/radionov/task_04/Stack_FIFO.java
Lesson_02/src/main/java/radionov/task_04/Stack_LIFO.java

Реализовал 2 класса:
1. FIFO
2. LIFO

Lesson02_Task04_LIFO_FIFO from Radionov

---

Lesson_02/src/main/java/radionov/task_03/Vector.java

Lesson02_Task03_Vectors from Radionov

---

Lesson_05/src/main/java/radionov/Sun.java
Lesson_05/src/main/java/radionov/TestSingletone.java

Реализация паттерна Singletone

Feature 05 sungletone by radionov

---

Lesson_04/src/main/java/sharoyko/Task_01/Main.java
Lesson_04/src/main/java/sharoyko/Task_01/Singleton.java

В задании 2 класса, реализация в классе Singleton, проверка в классе Main

Feature Lesson_04_Task_01: create Singleton

---

Lesson_03/src/main/java/chernoskutov/task_02/MyQueue.java
Lesson_03/src/main/java/chernoskutov/task_02/MyStack.java
Lesson_03/src/main/java/chernoskutov/task_02/Task_02.java

lesson3-task02 20191103

---

Lesson_03/src/main/java/shevnin/task_01/Vector_shevnin.java
Lesson_03/src/main/java/shevnin/task_02/Stack_shevnin.java

Shevnin lesson 03 2

---

Lesson_03/src/main/java/torikov/Task02Stack/Main.java
Lesson_03/src/main/java/torikov/Task02Stack/Stack.java
Lesson_03/src/main/java/torikov/Task03Queue/Main.java
Lesson_03/src/main/java/torikov/Task03Queue/Queue.java

Feature 03 03 torikov

---

Lesson_04/src/main/java/radionov/task02/BankFactory.java
Lesson_04/src/main/java/radionov/task02/BankProducts.java
Lesson_04/src/main/java/radionov/task02/Card.java
Lesson_04/src/main/java/radionov/task02/CreatorBankProducts.java
Lesson_04/src/main/java/radionov/task02/Credit.java
Lesson_04/src/main/java/radionov/task02/Deposit.java
Lesson_04/src/main/java/radionov/task02/Rko.java
Lesson_04/src/main/java/radionov/task02/SafeDepositBox.java
Lesson_04/src/main/java/radionov/task02/TypesProducts.java

Lesson04_Task02_Factory_by_Radionov

---

Lesson_04/src/main/java/polenok/task_01/Singleton.java
Lesson_04/src/main/java/polenok/task_01/Task_01.java

feature-04-polenok-task-01

---

Lesson_03/src/main/java/torikov/Task02Stack/Main.java
Lesson_03/src/main/java/torikov/Task02Stack/Stack.java

feature-03-02-torikov

---

Lesson_04/src/main/java/sharoyko/Task_02/Task_02_AbsFactory.java

Feature Lesson_04_Task_02: Create abstract factory

---

Lesson_03/src/main/java/kasyanov/Task_Queue.java
Lesson_03/src/main/java/kasyanov/Task_Stack.java
Lesson_04/src/main/java/kasyanov/Factory.java
Lesson_04/src/main/java/kasyanov/Singleton.java

Feature kasyanov task3

---

Lesson_04/src/main/java/tishchenko/task_02/CiscoHub.java
Lesson_04/src/main/java/tishchenko/task_02/CiscoIndustry.java
Lesson_04/src/main/java/tishchenko/task_02/CiscoRouter.java
Lesson_04/src/main/java/tishchenko/task_02/CiscoSwitch.java
Lesson_04/src/main/java/tishchenko/task_02/HuaweiHub.java
Lesson_04/src/main/java/tishchenko/task_02/HuaweiIndustry.java
Lesson_04/src/main/java/tishchenko/task_02/HuaweiRouter.java
Lesson_04/src/main/java/tishchenko/task_02/HuaweiSwitch.java
Lesson_04/src/main/java/tishchenko/task_02/Hub.java
Lesson_04/src/main/java/tishchenko/task_02/Industry.java
Lesson_04/src/main/java/tishchenko/task_02/Router.java
Lesson_04/src/main/java/tishchenko/task_02/Switch.java
Lesson_04/src/main/java/tishchenko/task_02/SwitchIndustry.java

Реализовал абстрактную фабрику

feature-Lesson_04-Task02-Tishchenko

---

Lesson_05/src/main/java/sarapulova/task_01/FindDupMain.java
Lesson_05/src/main/java/sarapulova/task_01/Funcs.java
Lesson_05/src/main/java/sarapulova/task_01/UserSber.java

Не смотрела твои подсказки, хотелось попробовать самой.
Думаю, не совсем корректно воспользовалась переопределением функций - хочу пояснений :)

feature-05-sarapulova find duplicate in collection

---

Lesson_05/src/main/java/tishchenko/task_01/FindDublicates.java
Lesson_05/src/main/java/tishchenko/task_01/UserSber.java

Реализовал поиск дублей в 2 коллекциях, среднее время поиска около 3 сек

feature-tishchenko-Lesson5_task01

---

Lesson_06/src/main/java/tishchenko/task01/reflection.java

Открытие метода с помощью Reflection API

feature-Lesson6-Task01-tishchenko

---

Lesson_05/src/main/java/kuzmina/task_01/Task_01.java
Lesson_06/src/main/java/radionov/Test.java

Задача на вызов private метода

feature-Lesson06-Reflection_by_Radionov

---

Lesson_06/src/main/java/polenok/Task_01.java

feature-06-polenok

---

Lesson_05/src/main/java/radionov/Main.java
Lesson_05/src/main/java/radionov/UserSber.java

Задача на нахождение дублей в массивах

Feature lesson5 by radionov
